server:
  port: 8081

spring:
#  application:
#    name: demo-consumer
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://discovery:8761/eureka/
    register-with-eureka: false
    fetch-registry: true
  instance:
    prefer-ip-address: true
